### ISSUE TITLE
Extension does not support high performance orders storage

### ISSUE THREAD

**Issue by ioxFR** [algoritmika/guest-order-tracking-for-woocommerce#1]
Hello,

Thanks for this great work on extension!
Currently, extension is not supporting High performance storage for orders.
Would be great to add support of this option in woocommerce!

Thanks in advance,
Rgds,
Valentin

**Comment by pablo-sg-pacheco** [comment]
Hi @ioxFR ,

Thanks :)

I just released a new version (2.1.5) today with HPOS compatibility.
